# Compile arguments
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
org.gradle.daemon=false

# Mod properties
mod_version = 1.0.7
mod_group = it.hurts.shatterbyte.immersiveui
mod_name = ImmersiveUI
mod_id = immersiveui
mod_description = Makes your UI flashy :D
mod_authors = Shatterbyte
mod_license = All Rights Reserved
mod_tracker = https://github.com/Octo-Studios/immersive-ui/issues
enabled_platforms = fabric

# Minecraft properties
minecraft_version = 26.2
minecraft_version_range = ~26.2
java_version = 25

# Dependencies
shatterlib_version = 0.7.0-beta.1+26.2
fabric_loader_version = 0.19.3
fabric_api_version = 0.152.1+26.2
modmenu_version = 20.0.0-beta.4
