pluginManagement {
    repositories {
        maven { name = 'Fabric'; url = 'https://maven.fabricmc.net' }
        mavenCentral()
        gradlePluginPortal()
    }
}

rootProject.name = 'immersiveui'

if (providers.gradleProperty('useLocalShatterLib').isPresent() && file('../octo-lib').isDirectory()) {
    includeBuild('../octo-lib') {
        dependencySubstitution {
            substitute module('it.hurts.shatterbyte.shatterlib:shatterlib-fabric') using project(':fabric')
        }
    }
}
